### ISSUE TITLE
ReferenceError: readFileSync is not defined

### ISSUE THREAD

**Issue by LucasBordoniRodrigues** [heydryft/tlsclient.js#4]
The module cannot be installed, this error occurs!

npm ERR! code 1
npm ERR! path /home/dev123/recap/node_modules/@dryft/tlsclient
npm ERR! command failed
npm ERR! command sh -c node ./scripts/postinstall.js
npm ERR! /home/dev123/recap/node_modules/@dryft/tlsclient/scripts/tlspath.js:21
npm ERR!   let releaseDetails = readFileSync("/etc/os-release", "utf8");
npm ERR!                        ^
npm ERR! 
npm ERR! ReferenceError: readFileSync is not defined
npm ERR!     at Object.<anonymous> (/home/dev123/recap/node_modules/@dryft/tlsclient/scripts/tlspath.js:21:24)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1241:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1091:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:938:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1115:19)
npm ERR!     at require (node:internal/modules/helpers:130:18)
npm ERR!     at Object.<anonymous> (/home/dev123/recap/node_modules/@dryft/tlsclient/scripts/postinstall.js:3:34)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1241:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node version: v20.9.0

**Comment by restocked** [comment]
Have you found any solution to this issue?

**Comment by Water224** [comment]
you ever find a fix for this?
